### ISSUE TITLE
Matlab 2019b support

### ISSUE THREAD

**Issue by ppisa** [CTU-IIG/ert_linux#3]
Thanks to help from Jan Houska from Humusoft, the project has been updated and tested  with Matlab/Simulink Release 2019b. Project continues to be used and maintained at Department of Control Engineering https://dce.fel.cvut.cz/ . See our repository

https://github.com/aa4cc/ert_linux

The master branch supports R2019b, the branch r2017a supports R2017a and possibly even older versions.  Report issues related to the updated project at linked repository.

**Comment by wentasah** [comment]
@ppisa Thank for working on this. I've added a link to your repository. However, it might be better to transfer ownership of this repository to aa4cc. The advantage would be that people are automatically redirected to the new repository and don't have to click on the link manually. Also, all issues and discussions will be preserved. It seems you already have permissions to do the transfer (https://help.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account), so feel free to move this repo. If you don't have permissions, let me know, I'll try to give them to you.

After the transfer, you can force-push the content of your repo over what's in here.
